### ISSUE TITLE
Exception not caught

### ISSUE THREAD

**Issue by Razzeee** [fuzeman/trakt.py#15]
I'm trying to auth and haven't set exceptions to true.
When I'm offline and try to auth I still get an error:

```
00:43:26 T:3964   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'requests.exceptions.ConnectionError'>
                                            Error Contents: ('Connection aborted.', gaierror(11001, 'getaddrinfo failed'))
                                            Traceback (most recent call last):
                                              File "C:\Users\razze\AppData\Roaming\Kodi\addons\script.trakt\default.py", line 15, in <module>
                                                traktService().run()
                                              File "C:\Users\razze\AppData\Roaming\Kodi\addons\script.trakt\service.py", line 104, in run
                                                globals.traktapi = traktAPI()
                                              File "C:\Users\razze\AppData\Roaming\Kodi\addons\script.trakt\traktapi.py", line 35, in __init__
                                                self.getToken()
                                              File "C:\Users\razze\AppData\Roaming\Kodi\addons\script.trakt\traktapi.py", line 60, in getToken
                                                auth = Trakt['auth'].login(getSetting('username'), getSetting('password'))
                                              File "C:\Users\razze\AppData\Roaming\Kodi\addons\script.trakt\trakt\interfaces\auth.py", line 10, in login
                                                'password': password
                                              File "C:\Users\razze\AppData\Roaming\Kodi\addons\script.trakt\trakt\core\http.py", line 89, in post
                                                return self.request('POST', path, params, data, **kwargs)
                                              File "C:\Users\razze\AppData\Roaming\Kodi\addons\script.trakt\trakt\core\http.py", line 66, in request
                                                response = self.session.send(prepared, timeout=timeout)
                                              File "C:\Users\razze\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\sessions.py", line 569, in send
                                                r = adapter.send(request, **kwargs)
                                              File "C:\Users\razze\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\adapters.py", line 407, in send
                                                raise ConnectionError(err, request=request)
                                            ConnectionError: ('Connection aborted.', gaierror(11001, 'getaddrinfo failed'))
                                            -->End of Python script error report<--
```

**Comment by fuzeman** [comment]
The plugin doesn't catch any exceptions from requests, the `exceptions` parameter is only to enable/disable the extra 5xx response exceptions.
