### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by He4dShOt** [fuzeman/trakt.py#2]
from trakt import Trakt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/trakt/__init__.py", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/trakt/client.py", line 1, in <module>
ImportError: No module named core.configuration

**Comment by fuzeman** [comment]
The version on PyPI appears to be missing some files.. will try get this fixed today.

**Comment by fuzeman** [comment]
This should be fixed in the latest release
